apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: autoscale-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - periodSeconds: 5
        type: Percent
        value: 100
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - periodSeconds: 5
        type: Percent
        value: 100go mod init pho
      - periodSeconds: 5
        type: Pods
        value: 5
      selectPolicy: Max
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Pods
    pods:
      metric:
        name: prometheus.googleapis.com|numJobs|gauge
      target:
        type: AverageValue
        averageValue: 1
